package com.myspace.proyectopruebasic;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Pedido")
public class Pedido implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Cliente")
	private com.myspace.proyectopruebasic.Cliente cliente;

	@org.kie.api.definition.type.Label(value = "Productos")
	private java.util.List<com.myspace.proyectopruebasic.Producto> productos;

	@org.kie.api.definition.type.Label(value = "Precio Total")
	private java.lang.Double precioTotal;

	public Pedido() {
	}

	public com.myspace.proyectopruebasic.Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(com.myspace.proyectopruebasic.Cliente cliente) {
		this.cliente = cliente;
	}

	public java.util.List<com.myspace.proyectopruebasic.Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(
			java.util.List<com.myspace.proyectopruebasic.Producto> productos) {
		this.productos = productos;
	}

	public java.lang.Double getPrecioTotal() {
		return this.precioTotal;
	}

	public void setPrecioTotal(java.lang.Double precioTotal) {
		this.precioTotal = precioTotal;
	}

	public Pedido(com.myspace.proyectopruebasic.Cliente cliente,
			java.util.List<com.myspace.proyectopruebasic.Producto> productos,
			java.lang.Double precioTotal) {
		this.cliente = cliente;
		this.productos = productos;
		this.precioTotal = precioTotal;
	}

}